"""initial migration

Revision ID: cce40d654265
Revises: 
Create Date: 2017-06-02 10:37:04.129658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce40d654265'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitecode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitecode',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invitation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'invitation', name='invitecode_pkey'),
    sa.UniqueConstraint('invitation', name='invitecode_invitation_key')
    )
    # ### end Alembic commands ###
